Repository stackrox/kube-linter, pull requests merged in 2023-04, with the labels that each got.

#535 Fix go install for newer golangs
  README.md
Labels: bug, documentation

#534 Improve privilage escalation remediation message
  docs/generated/checks.md
  pkg/builtinchecks/yamls/privilege-escalation.yaml
  pkg/templates/privilegeescalation/template.go
Labels: bug, documentation

#536 Use commit version instead of tag for openshift/api
  go.mod
  go.sum
Labels: bug, chore

#561 Add new checks section in release
  .github/release-drafter.yml
Labels: chore
